### ISSUE TITLE
-g breaks syscall

### ISSUE THREAD

**Issue by weiwenzhou** [sbustars/STARS#3] opened 2020-11-04 01:22 UTC
OS: Windows
Ran in: Git Bash and Windows Powershell

Running ``` python sbumips.py test.asm -g``` results in "InvalidSyscall: Not a valid syscall code"

**Comment by law-lin** [comment] 2020-11-04 19:01
OS: Windows
Env: Powershell

I'm also able to reproduce this.

**Comment by ipeitzsch** [comment] 2020-11-06 15:59
This issue was caused by an error in how registers were initialized. All registers were being randomized, when there is a subset of registers that are always 0 at the start. A fix has been made and will be pushed after further testing.

**Closed** 2020-11-10 17:55 UTC
